config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :penguins
  resources :colonies
  resources :scientists
  resources :login, only: [:new, :create]
  root to: 'application#welcome'
  get '/login', to: 'login#destroy', as: 'logout'
  get '/the-creation', to: 'application#creation', as: 'creation'
  patch '/add-fish/:id', to: 'penguins#feed_penguin', as: 'feeding'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/penguin.rb
class Penguin < ApplicationRecord
  belongs_to :colony
  validates :name, presence: true, uniqueness: true
  validates :title, presence: true
  validates :temp, presence: true
  # validates :alive, presence: true
  validates :species, presence: true

  def alive_or_dead
    if self.alive == true
      "✅ Alive"
    else
      "💐 Deceased"
    end
  end

  def assign_image
    image_array = [
      "https://imgur.com/8tO12W1.png",
      "https://imgur.com/o3LyKwR.png",
      "https://imgur.com/r3SUcTO.png",
      "https://imgur.com/r3SUcTO.png",
      "https://imgur.com/Q91Yx9k.png",
      "https://imgur.com/MjI1WK4.png",
      "https://imgur.com/SRw2DLJ.png",
      "https://imgur.com/ASY4lv9.png",
      "https://imgur.com/VkoA2Na.png",
      "https://imgur.com/EsXJN0n.png",
      "https://imgur.com/1Ad7Grs.png",
      "https://imgur.com/NMgET8f.png",
      "https://imgur.com/tKTdSjR.png",
      "https://imgur.com/BuhLwjs.png",
      "https://imgur.com/z2tTEui.png",
      "https://imgur.com/cSECvEk.png",
      "https://imgur.com/2atJlZp.png",
      "https://imgur.com/Uzt4IH0.png",
      "https://imgur.com/JdhLB9x.png",
      "https://imgur.com/2bLwXvL.png",
      "https://imgur.com/JE8BHN6.png",
      "https://imgur.com/P4TKiow.png",
      "https://imgur.com/gYTJeQy.png",
      "https://imgur.com/gW9EjbA.png",
      "https://imgur.com/GVOkST8.png"
    ]
    self.image_url = image_array.sample
  end

  def fish_counter
    self.fish += 1
  end

  def hungry?
    time_diff = Time.now - self.updated_at
    (time_diff / 1.minute).round
  end

end

app/controllers/penguins_controller.rb
class PenguinsController < ApplicationController

  def index
    @penguins = []
    @current_scientist.colonies.select {|colony| @penguins << colony.penguins }
    @penguins = @penguins.flatten.uniq
  end

  def show
    @penguin = Penguin.find(params[:id])
  end

  def new
    @penguin = Penguin.new
    @colonies = Colony.all
  end

  def create
    penguin = Penguin.create(penguin_params)
    if penguin.valid?
      penguin.update(image_url: penguin.assign_image)
      redirect_to penguin
    else
      flash[:errors] = penguin.errors.full_messages
      redirect_to new_penguin_path
    end
  end


  def edit
    @penguin = Penguin.find(params[:id])
    @colonies = Colony.all
  end

  def update
    @penguin = Penguin.find(params[:id])
    @penguin.update(edit_strong_params)
    redirect_to penguin_path(@penguin)
  end

  def destroy
    @penguin = Penguin.find(params[:id])
    colony = @penguin.colony
    @penguin.destroy
    redirect_to colony_path(colony)
  end

  def feed_penguin
    # byebug
    penguin = Penguin.find(params[:id])
    penguin.fish_counter
    penguin.update(fish: penguin.fish)
    redirect_to penguin
  end

  private

  def edit_strong_params
    params.require(:penguin).permit(:name, :title, :temp, :alive, :species)
  end

  def penguin_params
    params.require(:penguin).permit(:name, :title, :temp, :alive, :species, :colony_id)
  end

end

app/helpers/penguins_helper.rb
module PenguinsHelper
end

app/views/penguins/edit.html.erb
<div class="the_forms">
  <h1>Edit <%= @penguin.name %></h1>

  <p>
    <%= form_for @penguin do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label :temp, "Temperament" %><br>
    <%= f.text_field :temp %><br>
    <%= f.label :colony_id %><br>
    <%= f.collection_select :colony_id, @colonies, :id, :name %><br>
    <%= f.label :alive %><br>
    <%= f.check_box :alive, class: "checker"%><br>
    <%= f.label :species  %><br>
    <%= f.text_field :species %><br>
    <%= f.submit %>
    <% end %>
  </p>
</div>

app/views/penguins/index.html.erb
<div class="one">
  <div class="icon-bar">
    <%= link_to image_tag(('create_guin1.png'), :class => "edit_btn"), new_penguin_path %>
  </div>
</div>

<div class="three">
  <h1>Penguins</h1>
  <ul>
    <% @penguins.each do |penguin| %>
    <li>
      <%= link_to penguin.name, penguin %>
    </li>
    <% end  %>
  </ul>
</div>

app/views/penguins/new.html.erb
<div class="the_forms">
  <h1>Make A Penguin</h1>
  <% if flash[:errors] %>
    <h5>(｡•́ ⌔ •̀｡) Oh no... </h5>
      <ul>
        <% flash[:errors].each do |error| %>
          <li>
            <%= error %>
          </li>
        <%end %>
      </ul>
  <% end  %>
  <br>

  <%= form_for @penguin do |f| %>
  <%= f.label "Name" %><br>
    <%= f.text_field :name %><br>
    <br>
  <%= f.label "Title" %><br>
    <%= f.text_field :title %><br>
    <br>
  <%= f.label "Temperament" %><br>
    <%= f.text_field :temp %><br>
    <br>
  <%= f.label "Alive" %><br>
    <%= f.check_box :alive, class: "checker" %><br>
    <br>
  <%= f.label "Colony" %><br>
    <%= f.collection_select :colony_id, @colonies, :id, :name %><br>
    <br>
  <%= f.label "Species" %><br>
    <%= f.text_field :species %><br>
  <%= f.submit %>
  <% end  %>
</div>

app/views/penguins/show.html.erb
<div class="one">
  <div class="icon-bar">
    <%= link_to image_tag(('delete_guin1.png'), :class => "edit_btn"), penguin_path(@penguin), {method: :delete, data: { confirm: '(｡•́︿•̀｡) Are you sure?'} }%>
    <%= link_to image_tag(('edit_guin1.png'), :class => "edit_btn"), edit_penguin_path(@penguin) %>
    <%= link_to image_tag(('create_guin1.png'), :class => "edit_btn"), new_penguin_path %>

    <% if @penguin.alive == true %>
      <%= link_to image_tag(('fishy.gif'), :class => "edit_btn"), feeding_path(@penguin), method: :patch%>
    <% end  %>

  </div>
</div>

<div class="two">
  <img src="<%= @penguin.image_url %>" class="profile_pic">
</div>

<div class="three">
  <h1> <%= @penguin.name %> </h1>
  <div class="peng_profile">

    <h4>Title</h4>
    <p><%= @penguin.title %></p>

    <h4>Temperament</h4>
    <p><%= @penguin.temp  %></p>

    <h4>Status</h4>
    <p><%= @penguin.alive_or_dead %></p>

    <h4>Species</h4>
    <p><%= @penguin.species %></p>

    <% if @penguin.alive == true %>
      <h4>Fishes Eaten</h4>
      <p><%= @penguin.fish %></p>
    <% end %>

    <% if @penguin.hungry? > 1 && @penguin.alive == true%>
      <h4>Hunger</h4>
      <p>Please feed me 🐠 !</p>
    <% end  %>

    <h4>Colony</h4>
    <p><%= link_to  @penguin.colony.name, @penguin.colony, class:"peng_profile_2"%></p>

  </div>
</div>