config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :penguins
  resources :colonies
  resources :scientists
  resources :login, only: [:new, :create]
  root to: 'application#welcome'
  get '/login', to: 'login#destroy', as: 'logout'
  get '/the-creation', to: 'application#creation', as: 'creation'
  patch '/add-fish/:id', to: 'penguins#feed_penguin', as: 'feeding'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scientist.rb
class Scientist < ApplicationRecord
  has_secure_password
  has_many :records
  has_many :colonies, through: :records

  validates :name, presence: true
  validates :age, presence: true
  validates :bio, presence: true
  validates :username, presence: true, uniqueness: true

  def hungry_pengs
    @colonies = self.colonies
    @pengs = @colonies.map {|colony| colony.penguins}.flatten
    @pengs.select {|p| p.hungry? > 1}
  end

end

app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController
  skip_before_action :find_scientist, only: [:new, :create]

  def new
    @scientist = Scientist.new
  end

  def create
    @scientist = Scientist.create(scientist_strong_params)
    if @scientist.valid?
      session[:scientist_id] = @scientist.id
      redirect_to @scientist
    else
      flash[:errors] = @scientist.errors.full_messages
      redirect_to new_scientist_path
    end
  end

  def show
    @scientist = Scientist.find(params[:id])
  end

  def records
    # @scientist = Scientist.find(params[:id])
    # @records = @scientist.records
  end

  def edit
  end

  def update
    @current_scientist.update(edit_params)
    redirect_to @current_scientist
  end

  def destroy
    # @scientist = Scientist.find(params[:id])
    @current_scientist.destroy
    logout
    redirect_to welcome_path
  end

  private

  def edit_params
    params.require(:scientist).permit(:name, :age, :bio)
  end

  def record_params
    params.require(:record).permit(:scientist_id, :colony_id, :location, :project_name)
  end

  def scientist_strong_params
    params.require(:scientist).permit(:name, :age, :bio, :username, :password)
  end

end

app/helpers/scientists_helper.rb
module ScientistsHelper
end

app/views/scientists/edit.html.erb
<div class="the_forms">
  <h1>Edit <%= @current_scientist.name %>'s profile</h1>

  <%= form_for @current_scientist do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :age %><br>
  <%= f.number_field :age %><br>
  <%= f.label :bio %><br>
  <%= f.text_area :bio %><br>
  <%= f.submit "Submit Updates?" %>
  <% end %>
</div>

app/views/scientists/new.html.erb
<div class="the_forms">

  <h1>New User</h1>
    <% if flash[:errors] %>
      <div class="the_errors">
      <h3>(｡•́ ⌔ •̀｡) Oh no... </h3>
        <ul>
          <% flash[:errors].each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <%= form_for @scientist do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :age %><br>
  <%= f.number_field :age %><br>
  <%= f.label :bio %><br>
  <%= f.text_field :bio %><br>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.submit %>
  <% end  %>

</div>

app/views/scientists/records.html.erb
<h1>Records</h1>
<ul>
  <% @records.each do |record| %>
  <li>
    <%= link_to record.project_name, record %>
  </li>
  <% end  %>
</ul>

<%= button_to "Create New Record", new_record_path, method: :get %>

app/views/scientists/show.html.erb
<div class="one">
  <div class="icon-bar">
    <%= link_to image_tag(('delete_guin1.png'), :class => "edit_btn"), scientist_path(@current_scientist), {method: :delete, data: { confirm: '(｡•́︿•̀｡) Are you sure?'} }%>
    <%= link_to image_tag(('edit_guin1.png'), :class => "edit_btn"), edit_scientist_path(@current_scientist) %>
  </div>
</div>

<div class="two">
  <%= image_tag('Man_penguin_profile.png', :class => 'profile_pic') %>
</div>


<div class="three">
  <div class="" align="left" margin: 0 0 $small-spacing;>
    <h1> <%= @current_scientist.name %> </h1>

    <h4>Age</h4>
    <p> <%= @current_scientist.age %> </p>

    <h4>Bio</h4>
    <p> <%= @current_scientist.bio %> </p>
  </div>
</div>