config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :penguins
  resources :colonies
  resources :scientists
  resources :login, only: [:new, :create]
  root to: 'application#welcome'
  get '/login', to: 'login#destroy', as: 'logout'
  get '/the-creation', to: 'application#creation', as: 'creation'
  patch '/add-fish/:id', to: 'penguins#feed_penguin', as: 'feeding'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :find_scientist, except: [:welcome]

  def welcome
  end

  def creation
  end

  def find_scientist
    @scientist_id = session[:scientist_id]
    @logged_in = !!@scientist_id
    if @logged_in
      @current_scientist = Scientist.find(@scientist_id)
      @records = @current_scientist.records
    else
      flash[:messages] = "You need to be logged in!"
      redirect_to root_path
    end
  end

  def logout
    session[:scientist_id] = nil
  end

  # def pop_up
  #   @the_pengs = @current_scientist.hungry_pengs
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/creation.html.erb
<div class="adam_box">
  <%= link_to image_tag(('adam_creation.jpg'), class:"adam"), @current_scientist%>
</div>

app/views/application/welcome.html.erb
<div class="the_forms">
  <div class="the_title">
    <h1>Penguino</h1>
  </div>

<br>
  <h5>Click on a penguin to enter!</h5>

  <% if flash[:messages] %>
    <h5> (｡•́ ⌔ •̀｡) Oh no...  </h5>
      <ul>
          <li>
            <%= flash[:messages] %>
          </li>
      </ul>
  <% end %>

<div class="welcome_bttn">
  <%= link_to image_tag(('thumbnail.png'), class: "mama"), new_login_path %>
  <%= link_to image_tag(('bb_penguin.png'), class: "baby"), new_scientist_path %>
  <div class="welcome_bttn">
    <div class="login_label"><p>Login</p></div>
    <div class="register_label"><p>New User</p></div>
  </div>
</div>


</div>