config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :penguins
  resources :colonies
  resources :scientists
  resources :login, only: [:new, :create]
  root to: 'application#welcome'
  get '/login', to: 'login#destroy', as: 'logout'
  get '/the-creation', to: 'application#creation', as: 'creation'
  patch '/add-fish/:id', to: 'penguins#feed_penguin', as: 'feeding'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Penguino</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if @current_scientist %>
      <header >
        <a href=" <%= creation_path %> " class="logo_link">
          <%= image_tag "penguin_logo.jpg", class: "guin_logo" %>
            <%= "Logged in as #{@current_scientist.username}" %>
        </a>
        <nav>
          <ul class="nav_links">
            <li><a href=" <%= scientist_path(@current_scientist)  %>   ">Profile</a>  </li>
            <li><a href=" <%= records_path  %>   ">Records</a>  </li>
            <li><a href=" <%= colonies_path  %>  ">Colony</a>  </li>
            <li><a href=" <%= penguins_path  %>  ">Penguins</a>  </li>
            <!-- <li><a href=" <%= logout_path %> ">Logout</a></li> -->
            <a href=" <%= logout_path %>"> <button type="button" name="button"> Log Out </button> </a>
          </ul>
        </nav>
      </header>

      <% if @current_scientist.hungry_pengs %>
      <h3>PLEASE FEED THEM:</h3>
      <% @current_scientist.hungry_pengs.each do |peng| %>
      <ul>
        <li>
          <%= peng.name %>
        </li>
      </ul>
      <% end  %>
    <% end %>
    <% end %>
    <div class="background">
      <div class='container'>

        <%= yield %>
      </div>
    </div>
  </body>
</html>